import { useState } from 'react'
import { Link2, Download, Check } from 'lucide-react'

/* Turn a URL into something readable. Falls back to the raw string for
   values the model returned as a platform name rather than a link. */
function sourceLabel(value) {
  if (!value) return null
  try {
    const u = new URL(value)
    const path = u.pathname.replace(/\/$/, '')
    const short = path.length > 28 ? `${path.slice(0, 28)}…` : path
    return u.hostname.replace(/^www\./, '') + short
  } catch {
    return value.length > 48 ? `${value.slice(0, 48)}…` : value
  }
}

function isUrl(value) {
  return typeof value === 'string' && /^https?:\/\//.test(value)
}

function Source({ value }) {
  const label = sourceLabel(value)
  if (!label) return null
  if (!isUrl(value)) return <span className="source">{label}</span>
  return (
    <a className="source" href={value} target="_blank" rel="noopener noreferrer" title={value}>
      <Link2 size={11} strokeWidth={1.75} />
      {label}
    </a>
  )
}

function Level({ value }) {
  if (!value) return null
  return (
    <span className="pill" data-level={String(value).toLowerCase()}>
      {value}
    </span>
  )
}

/* Backend cross-checks this item's cited source/name against the raw search
   results it was given — this renders when that check failed. */
function Unverified({ verified }) {
  if (verified !== false) return null
  return (
    <span
      className="tag"
      title="This wasn't found in the search results the model was given — treat it with caution."
    >
      unverified
    </span>
  )
}

function verdictKey(verdict = '') {
  const v = verdict.toLowerCase()
  if (v.includes('strong')) return 'strong'
  if (v.includes('weak')) return 'weak'
  return 'moderate'
}

function humanise(key) {
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()).trim()
}

function AnalysisResults({ idea, results, analysisType }) {
  const [activeTab, setActiveTab] = useState(0)
  const [checkedItems, setCheckedItems] = useState(new Set())

  const toggleCheckItem = (itemId) => {
    setCheckedItems((prev) => {
      const next = new Set(prev)
      next.has(itemId) ? next.delete(itemId) : next.add(itemId)
      return next
    })
  }

  const parseData = (data) => {
    if (!data) return null
    if (typeof data === 'string') {
      try {
        return JSON.parse(data)
      } catch {
        return data
      }
    }
    return data
  }

  /* ── PDF export via the browser print dialog ───────────────────────────── */

  const printableHTML = (pitchDeck) => `<!DOCTYPE html>
<html><head><meta charset="utf-8" /><title>${idea}</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Inter, -apple-system, sans-serif; color: #16150f; background: #fff;
         font-size: 11pt; line-height: 1.55; padding: 48px; }
  h1 { font-family: 'Instrument Serif', Georgia, serif; font-weight: 400; font-size: 30pt;
       line-height: 1.1; letter-spacing: -0.01em; max-width: 20ch; }
  .meta { margin-top: 10px; font-size: 9pt; color: #8a877b; }
  .summary { margin: 28px 0 40px; padding: 16px 20px; border-left: 2px solid #16150f;
             max-width: 68ch; }
  .slide { padding-top: 22px; margin-top: 22px; border-top: 1px solid #e3e1d9;
           page-break-inside: avoid; }
  .slide-head { display: flex; align-items: baseline; gap: 10px; margin-bottom: 12px; }
  .num { font-size: 8pt; color: #8a877b; letter-spacing: .08em; }
  .slide h2 { font-family: 'Instrument Serif', Georgia, serif; font-weight: 400; font-size: 17pt; }
  .field { margin-top: 12px; }
  .field-label { font-size: 8pt; letter-spacing: .09em; text-transform: uppercase; color: #8a877b; }
  .field p, .field li { max-width: 66ch; color: #55534a; margin-top: 3px; }
  .field ul { padding-left: 16px; }
  @page { margin: 16mm; }
</style></head><body>
  <h1>${idea}</h1>
  <p class="meta">Pitch narrative generated by JustExecute</p>
  ${
    pitchDeck.executiveSummary
      ? `<div class="summary"><p>${pitchDeck.executiveSummary}</p></div>`
      : ''
  }
  ${pitchDeck.slides
    .map(
      (slide, i) => `
    <section class="slide">
      <div class="slide-head">
        <span class="num">${String(slide.slideNumber || i + 1).padStart(2, '0')}</span>
        <h2>${slide.title || ''}</h2>
      </div>
      ${Object.entries(slide.content || {})
        .filter(([, v]) => v)
        .map(([k, v]) =>
          Array.isArray(v)
            ? `<div class="field"><div class="field-label">${humanise(k)}</div><ul>${v
                .map((item) => `<li>${item}</li>`)
                .join('')}</ul></div>`
            : `<div class="field"><div class="field-label">${humanise(k)}</div><p>${v}</p></div>`
        )
        .join('')}
    </section>`
    )
    .join('')}
</body></html>`

  const exportPdf = (pitchDeck) => {
    if (!pitchDeck?.slides?.length) return
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(printableHTML(pitchDeck))
    w.document.close()
    setTimeout(() => w.print(), 600)
  }

  /* ── Simple / tools modes ──────────────────────────────────────────────── */

  const renderSimpleResults = () => {
    const analysis = results.analysis || results
    if (typeof analysis !== 'object') {
      return (
        <div className="pane response-text">
          <p>{analysis}</p>
        </div>
      )
    }

    const fields = [
      ['Summary', analysis.summary],
      ['Target market', analysis.targetMarket],
      ['Unique value', analysis.uniqueValue],
      ['Challenges', analysis.challenges],
      ['Opportunities', analysis.opportunities],
      ['Next steps', analysis.nextSteps],
    ].filter(([, value]) => value)

    return (
      <div className="pane">
        {fields.map(([label, value]) => (
          <section className="block" key={label}>
            <h3 className="block-title">{label}</h3>
            {Array.isArray(value) ? (
              <ul className="bullets">
                {value.map((v, i) => (
                  <li key={i}>{v}</li>
                ))}
              </ul>
            ) : (
              <p className="prose muted">{value}</p>
            )}
          </section>
        ))}
      </div>
    )
  }

  const renderToolsResults = () => (
    <div className="pane">
      <section className="block">
        <span className="label">{results.toolCallsCount || 0} web searches</span>
        <div className="response-text" style={{ marginTop: '1rem' }}>
          {results.response?.split('\n').map(
            (para, i) => para.trim() && <p key={i}>{para}</p>
          )}
        </div>
      </section>
    </div>
  )

  /* ── Deep research ─────────────────────────────────────────────────────── */

  const renderAgentResults = () => {
    const marketValidation = parseData(results.marketValidation)
    const competitors = parseData(results.competitors)
    const gtmStrategy = parseData(results.gtmStrategy)
    const risks = parseData(results.risks)
    const executionPlan = parseData(results.executionPlan)

    const tabs = [
      ['Market', marketValidation],
      ['Competitors', competitors],
      ['Go-to-market', gtmStrategy],
      ['Risk', risks],
      ['Execution', executionPlan],
    ]

    const panes = [
      /* 0 — Market validation */
      () => {
        const mv = marketValidation
        if (typeof mv === 'string') return <p className="prose">{mv}</p>
        if (mv?.error) {
          return (
            <section className="block">
              <h3 className="block-title">Market research unavailable</h3>
              <p className="prose muted">{mv.error}</p>
            </section>
          )
        }
        const demand = mv.demandScore
        const market = mv.marketAnalysis
        const pain = mv.evidence?.painSignals || []
        const seeking = mv.evidence?.solutionSeeking || []

        return (
          <>
            {mv.summary && (
              <section className="block">
                <p className="lead-para">{mv.summary}</p>
                {mv.researchNote && (
                  <p className="muted" style={{ marginTop: '0.75rem', fontSize: '0.8125rem' }}>
                    {mv.researchNote}
                  </p>
                )}
              </section>
            )}

            {demand && (
              <section className="block">
                <h3 className="block-title">Demand verdict</h3>
                <div className="verdict" data-verdict={verdictKey(demand.overallVerdict)}>
                  <span className="verdict-value">{demand.overallVerdict}</span>
                  {demand.confidenceLevel && (
                    <span className="tag">{demand.confidenceLevel} confidence</span>
                  )}
                </div>
                {demand.recommendation && (
                  <p className="verdict-note">{demand.recommendation}</p>
                )}
              </section>
            )}

            {market && (
              <section className="block">
                <h3 className="block-title">Market data</h3>
                <dl className="deflist">
                  {[
                    ['Market size', market.tamSize],
                    ['Growth', market.growthRate],
                    ['Pain level', market.customerPain],
                  ]
                    .filter(([, v]) => v)
                    .map(([term, value]) => (
                      <div className="deflist-row" key={term}>
                        <dt className="label">{term}</dt>
                        <dd>{value}</dd>
                      </div>
                    ))}
                </dl>
              </section>
            )}

            {pain.length > 0 && (
              <section className="block">
                <h3 className="block-title">Pain signals found</h3>
                <div className="evidence">
                  {pain.map((s, i) => (
                    <figure className="quote" key={i}>
                      <blockquote>{s.quote}</blockquote>
                      <figcaption className="quote-foot">
                        <Source value={s.source} />
                        <Unverified verified={s.verified} />
                        <Level value={s.painLevel} />
                      </figcaption>
                    </figure>
                  ))}
                </div>
              </section>
            )}

            {seeking.length > 0 && (
              <section className="block">
                <h3 className="block-title">People asking for a solution</h3>
                <div className="evidence">
                  {seeking.map((s, i) => (
                    <figure className="quote" key={i}>
                      <blockquote>{s.query}</blockquote>
                      {s.context && (
                        <p className="muted" style={{ marginTop: '0.5rem', fontSize: '0.875rem' }}>
                          {s.context}
                        </p>
                      )}
                      <figcaption className="quote-foot">
                        <Source value={s.source} />
                        <Unverified verified={s.verified} />
                      </figcaption>
                    </figure>
                  ))}
                </div>
              </section>
            )}
          </>
        )
      },

      /* 1 — Competitors */
      () => {
        const c = competitors
        if (typeof c === 'string') return <p className="prose">{c}</p>
        return (
          <>
            {c.marketGap && (
              <section className="block">
                <h3 className="block-title">The gap</h3>
                <div className="callout">
                  <p>{c.marketGap}</p>
                  {c.entryStrategy && (
                    <p>
                      <strong>Wedge:</strong> {c.entryStrategy}
                    </p>
                  )}
                </div>
              </section>
            )}

            {(c.marketDominance || c.bigTechThreat) && (
              <section className="block">
                <div className="cards">
                  {c.marketDominance && (
                    <div className="card">
                      <h4>Market dominance</h4>
                      {c.marketDominance.leader ? (
                        <>
                          <p>
                            <strong>Leader:</strong> {c.marketDominance.leader}
                          </p>
                          {c.marketDominance.marketShare && (
                            <p>{c.marketDominance.marketShare}</p>
                          )}
                          {c.marketDominance.moatStrength && (
                            <p>
                              <strong>Moat:</strong> {c.marketDominance.moatStrength}
                            </p>
                          )}
                        </>
                      ) : (
                        <p>No clear leader yet.</p>
                      )}
                    </div>
                  )}

                  {c.bigTechThreat && (
                    <div className="card">
                      <h4>
                        Big tech threat <Level value={c.bigTechThreat.riskLevel} />
                      </h4>
                      {c.bigTechThreat.timeline && (
                        <p>
                          <strong>Timeline:</strong> {c.bigTechThreat.timeline}
                        </p>
                      )}
                      {c.bigTechThreat.preventionStrategy && (
                        <p>{c.bigTechThreat.preventionStrategy}</p>
                      )}
                    </div>
                  )}
                </div>
              </section>
            )}

            {c.directCompetitors?.length > 0 && (
              <section className="block">
                <h3 className="block-title">Existing solutions</h3>
                <div className="rows">
                  {c.directCompetitors.map((comp, i) => (
                    <article className="row-item" key={i}>
                      <div className="row-head">
                        <span className="row-name">{comp.name}</span>
                        <span className="row-meta">
                          <Unverified verified={comp.verified} />
                          {comp.pricing}
                        </span>
                      </div>
                      {comp.description && <p>{comp.description}</p>}
                      {comp.weaknesses && (
                        <p className="note">
                          <strong>Vulnerability:</strong> {comp.weaknesses}
                        </p>
                      )}
                    </article>
                  ))}
                </div>
              </section>
            )}

            {c.workarounds?.length > 0 && (
              <section className="block">
                <h3 className="block-title">What people do instead</h3>
                <div className="rows">
                  {c.workarounds.map((w, i) => (
                    <article className="row-item" key={i}>
                      <div className="row-head">
                        <span className="row-name">{w.method}</span>
                      </div>
                      {w.painWithWorkaround && <p>{w.painWithWorkaround}</p>}
                    </article>
                  ))}
                </div>
              </section>
            )}
          </>
        )
      },

      /* 2 — Go-to-market */
      () => {
        const g = gtmStrategy
        if (typeof g === 'string') return <p className="prose">{g}</p>
        return (
          <>
            {g.valueProposition && (
              <section className="block">
                <p className="lead-para">{g.valueProposition}</p>
              </section>
            )}

            {g.targetAudience && (
              <section className="block">
                <h3 className="block-title">Target audience</h3>
                <p className="prose muted">{g.targetAudience}</p>
              </section>
            )}

            {g.earlyUserCommunities?.length > 0 && (
              <section className="block">
                <h3 className="block-title">Where the first users are</h3>
                <div className="rows">
                  {g.earlyUserCommunities.map((comm, i) => (
                    <article className="row-item" key={i}>
                      <div className="row-head">
                        <span className="row-name">{comm.name}</span>
                        <span className="row-meta">
                          <Unverified verified={comm.verified} />
                          {comm.platform}
                          <Level value={comm.relevance} />
                        </span>
                      </div>
                      {comm.strategy && <p>{comm.strategy}</p>}
                    </article>
                  ))}
                </div>
              </section>
            )}

            {g.channels?.length > 0 && (
              <section className="block">
                <h3 className="block-title">Channels</h3>
                <div className="rows">
                  {g.channels.map((ch, i) => (
                    <article className="row-item" key={i}>
                      <div className="row-head">
                        <span className="row-name">{ch.channel || ch.name}</span>
                        <Level value={ch.priority} />
                      </div>
                      {ch.strategy && <p>{ch.strategy}</p>}
                    </article>
                  ))}
                </div>
              </section>
            )}

            {g.launchStrategy && (
              <section className="block">
                <h3 className="block-title">Launch</h3>
                <p className="prose muted">{g.launchStrategy}</p>
              </section>
            )}
          </>
        )
      },

      /* 3 — Risk */
      () => {
        const r = risks
        if (typeof r === 'string') return <p className="prose">{r}</p>

        const groups = [
          ['Market risks', r.marketRisks, 'probability', 'mitigation', 'Mitigation'],
          ['Execution risks', r.executionRisks, 'probability', 'earlyWarning', 'Warning signs'],
          ['Competitive threats', r.competitiveThreats, 'timeline', 'response', 'Response'],
        ]

        return (
          <>
            {(r.mortalityScore || r.primaryDeathRisk) && (
              <section className="block">
                {r.mortalityScore && (
                  <div className="verdict" style={{ marginBottom: '1rem' }}>
                    <span className="label">Death risk score</span>
                    <span className="verdict-value">{r.mortalityScore}</span>
                  </div>
                )}
                {r.primaryDeathRisk && (
                  <div className="callout">
                    <p>
                      <strong>Most likely failure:</strong> {r.primaryDeathRisk}
                    </p>
                  </div>
                )}
              </section>
            )}

            {(r.criticalAssumptions?.length > 0 || r.survivalStrategy) && (
              <section className="block">
                <div className="cards">
                  {r.criticalAssumptions?.length > 0 && (
                    <div className="card">
                      <h4>Critical assumptions</h4>
                      <ul className="bullets" style={{ paddingLeft: '1rem' }}>
                        {r.criticalAssumptions.map((a, i) => (
                          <li key={i}>{a}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {r.survivalStrategy && (
                    <div className="card">
                      <h4>Survival strategy</h4>
                      <p>{r.survivalStrategy}</p>
                    </div>
                  )}
                </div>
              </section>
            )}

            {groups.map(([title, items, metaKey, noteKey, noteLabel]) =>
              items?.length > 0 ? (
                <section className="block" key={title}>
                  <h3 className="block-title">{title}</h3>
                  <div className="rows">
                    {items.map((item, i) => (
                      <article className="row-item" key={i}>
                        <div className="row-head">
                          <span className="row-name">{item.risk || item.threat}</span>
                          <Level value={item[metaKey]} />
                        </div>
                        {item[noteKey] && (
                          <p className="note">
                            <strong>{noteLabel}:</strong> {item[noteKey]}
                          </p>
                        )}
                      </article>
                    ))}
                  </div>
                </section>
              ) : null
            )}
          </>
        )
      },

      /* 4 — Execution */
      () => {
        const e = executionPlan
        if (typeof e === 'string') return <p className="prose">{e}</p>
        const deck = e.pitchDeck
        const periodTitles = {
          week1: 'Week 1',
          week2to4: 'Weeks 2–4',
          month2to3: 'Months 2–3',
        }

        return (
          <>
            {e.checklist && (
              <section className="block">
                <h3 className="block-title">Next 90 days</h3>
                <div className="check-groups">
                  {Object.entries(e.checklist).map(([period, items]) =>
                    items?.length ? (
                      <div className="check-group" key={period}>
                        <h4>{periodTitles[period] || humanise(period)}</h4>
                        {items.map((item, i) => {
                          const id = `${period}-${i}`
                          const checked = checkedItems.has(id)
                          return (
                            <button
                              type="button"
                              key={id}
                              className="check-item"
                              aria-pressed={checked}
                              onClick={() => toggleCheckItem(id)}
                            >
                              <span className="check-box">
                                <Check size={11} strokeWidth={3} />
                              </span>
                              <span className="check-text">{item.task || item}</span>
                              {item.priority && <Level value={item.priority} />}
                            </button>
                          )
                        })}
                      </div>
                    ) : null
                  )}
                </div>
              </section>
            )}

            {deck?.slides?.length > 0 && (
              <section className="block">
                <div className="row-head" style={{ marginBottom: '1rem' }}>
                  <h3 className="block-title" style={{ margin: 0 }}>
                    Pitch narrative
                  </h3>
                  <button className="btn btn-sm" onClick={() => exportPdf(deck)}>
                    <Download size={13} strokeWidth={1.75} />
                    Export PDF
                  </button>
                </div>

                {deck.executiveSummary && (
                  <div className="callout" style={{ marginBottom: '1.5rem' }}>
                    <p>{deck.executiveSummary}</p>
                  </div>
                )}

                <div className="slides">
                  {deck.slides.map((slide, i) => (
                    <article className="slide" key={i}>
                      <div className="slide-head">
                        <span className="label">
                          {String(slide.slideNumber || i + 1).padStart(2, '0')}
                        </span>
                        <h4>{slide.title}</h4>
                      </div>
                      {Object.entries(slide.content || {})
                        .filter(([, v]) => v)
                        .map(([key, value]) => (
                          <div className="slide-field" key={key}>
                            <span className="label">{humanise(key)}</span>
                            {Array.isArray(value) ? (
                              <ul>
                                {value.map((v, idx) => (
                                  <li key={idx}>{v}</li>
                                ))}
                              </ul>
                            ) : (
                              <p>{value}</p>
                            )}
                          </div>
                        ))}
                    </article>
                  ))}
                </div>
              </section>
            )}
          </>
        )
      },
    ]

    return (
      <>
        <div className="tabs" role="tablist">
          {tabs.map(([label, data], i) => (
            <button
              key={label}
              role="tab"
              className="tab"
              aria-selected={activeTab === i}
              disabled={!data}
              onClick={() => setActiveTab(i)}
            >
              {label}
            </button>
          ))}
        </div>
        <div className="pane" role="tabpanel">
          {tabs[activeTab][1] ? panes[activeTab]() : <p className="muted">Nothing returned for this step.</p>}
        </div>
      </>
    )
  }

  const modeLabel =
    analysisType === 'simple'
      ? 'Quick take'
      : analysisType === 'tools'
        ? 'Web search'
        : 'Deep research'

  return (
    <section className="results">
      <div className="results-head">
        <h2 className="serif">&ldquo;{idea}&rdquo;</h2>
        <span className="tag">{modeLabel}</span>
      </div>

      {analysisType === 'simple' && renderSimpleResults()}
      {analysisType === 'tools' && renderToolsResults()}
      {analysisType === 'agent' && renderAgentResults()}
    </section>
  )
}

export default AnalysisResults
